<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<div class="innerBanner">
<img src='<?php echo $this->getViewFileUrl('Tech9logy_Tathastu::img/Damo-Theme-Home-Page-Banner-Design-2.jpg'); ?>' alt="" class="img-responsive">
    <div class="bannerText"><h1>My account</h1>
     <div class="breadcrumb_top">
        <ul id="breadcrumbs" class="breadcrumbs"><li class="item-home"><a class="bread-link bread-home" href="<?= $block->escapeUrl($block->getUrl('')) ?>" title="Home">Home</a></li><li class="separator separator-home"> / </li><li class="item-current item-9"><strong class="bread-current bread-9"> My account</strong></li></ul>      </div>
    </div>
</div>
<div class="woocommerce"><div class="woocommerce-notices-wrapper"></div>
<form class="form password forget"
      action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field note"><?= $block->escapeHtml(__('Lost your password? Please enter your username or email address. You will receive a link to create a new password via email.')) ?></div>
        <div class="field email required">
            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Username or email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
           <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Reset password')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "form-validate"
            }
        }
    }
</script>

<script>
require(["jquery"], function ($) {
    // Reload captcha when page loaded
    $(window).bind("load", function() {
        // Use setTimeout to trigger captcha reload. 
        $(".action.captcha-reload").trigger("click");
    });
});
</script>
<style>
    .page-layout-1column .innerBanner {
  z-index: 1;
}
    .innerBanner .bannerText {
    position: absolute;
    bottom: 19%;
    left: 0;
    right: 0;
    letter-spacing: 0.6px;
    padding: 0 15px;
    margin: auto;
    text-align: center;
    font-weight: 700;
    color: #fff;
    text-transform: uppercase;
    z-index: 9;
    font-family: 'Gotu', sans-serif;
}
.customer-account-forgotpassword .innerBanner {
		overflow: hidden;
		height: 266px;
		position: relative;
  background: #fff !important;
}
.innerBanner img {
    height: 266px;
    object-fit: cover;
    width: 100%;
    opacity: 0.6;
}
.action.submit.primary {
    font-size: 100%;
    margin: 0;
    line-height: 1;
    cursor: pointer;
    position: relative;
    text-decoration: none;
    overflow: visible;
    padding: 0.618em 1em;
    font-weight: 700;
    border-radius: 3px;
    left: auto;
    color: #515151;
    background-color: #ebe9eb;
    border: 0;
    display: inline-block;
    background-image: none;
    box-shadow: none;
    text-shadow: none;
}
.innerBanner .bannerText h1 {
    font-size: 39px;
    font-weight: 500;
    color: #fff;
    letter-spacing: 2px;
}
.innerBanner .bannerText h1, .breadcrumbs li a, .innerBanner .bannerText .breadcrumbs li {
    color: #000 !important;
}
.breadcrumbs {
    padding: 0;
}
.innerBanner .bannerText .breadcrumbs li {
    color: #000 !important;
}
.customer-account-forgotpassword .page-title-wrapper {
    display: none;
}
.woocommerce {
    background: #fff;
    padding: 26px;
    border: 0 solid #ccc;
    -webkit-box-shadow: 0px 0px 6px 1px rgb(0 0 0 / 10%);
    -moz-box-shadow: 0px 0px 6px 1px rgba(0,0,0,0.1);
    box-shadow: 0px 0px 6px 1px rgb(0 0 0 / 10%);
}
.form.password.forget .fieldset::after {
  margin-top: 0px !important;
}
.customer-account-forgotpassword .woocommerce {
width: 100%;
max-width: 700px;
margin: 0 auto;
}
.actions-toolbar > .secondary .action.back {
  display: unset !important;
}
.customer-account-forgotpassword .woocommerce .actions-toolbar {
  float: unset;
  justify-content: space-between;
  display: flex;
}
.customer-account-forgotpassword .woocommerce .actions-toolbar .secondary {
width: 50%;
padding-top: 7px;
}
.customer-account-forgotpassword .woocommerce .actions-toolbar .primary {
width: 50%;
}
.customer-account-forgotpassword .actions-toolbar  .secondary span {
  color: #f47d2b !important; 
}
@media screen and (max-width: 768px) {
    .customer-account-forgotpassword .woocommerce .actions-toolbar .secondary span {
     float: left;
     }
     .customer-account-forgotpassword .woocommerce .actions-toolbar .secondary {
        width: 100%;
        padding-top: 7px;
        }
        .customer-account-forgotpassword .woocommerce .actions-toolbar .primary {
            width: 100%;
        }
        .customer-account-forgotpassword .woocommerce .actions-toolbar {
                float: unset;
                justify-content: space-between;
                display: block;
        }
}
    </style>
